<?php
// $Id: role_theme_switcher.module,v 1.7 2010/11/28 17:55:24 tiutiun Exp $

/**
 * Implementation of hook_custom_theme()
 */
function role_theme_switcher_custom_theme()
{
  global $user;
  $custom_theme = NULL;

  foreach ($user->roles as $id => $role)
  {
    $role_theme = variable_get('role_theme_switcher_'.$id.'_theme', '');

    if ($role_theme != 'Default')
    {
      $custom_theme = $role_theme;
    }
  }

  return array($custom_theme);
}

/**
 * Implementation of hook_menu()
 */
function role_theme_switcher_menu()
{
  $items['admin/people/permissions/themes'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Role theme switcher',
    'description'     => 'Settings for role theme switcher.',
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('role_theme_switcher_admin_settings'),
    'access arguments'=> array('administer site configuration'),
  );

  return $items;
}

/**
 * Implementation of hook_settings()
 */
function role_theme_switcher_admin_settings()
{
  $roles = user_roles();

  // Get all themes
  $themes = list_themes();
  $themes_list = array_merge(array('Default'), array_keys($themes));

  foreach ($roles as $id => $role)
  {
    $form['role_theme_switcher_'.$id.'_theme'] = array(
       '#type'          => 'select',
       '#title'         => ucfirst(strtolower($role)),
       '#options'       => drupal_map_assoc($themes_list),
       '#default_value' => variable_get('role_theme_switcher_'.$id.'_theme', '')
    );
  }

  return system_settings_form($form);
}
